config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "welcome#index"

  get "about_us", to: "welcome#about"
  get "history", to: "welcome#history"
  get "news", to: "welcome#news"
  get "resources", to: "welcome#resources"

  # Errors routes
  match "/404", to: "errors#not_found", via: :all
  match "/418", to: "errors#teapot", via: :all
  match "/422", to: "errors#unprocessable_content", via: :all
  match "/500", to: "errors#internal_server", via: :all

  resources :dashboard, only: :index do
    collection do
      get :settings
      resources :audit_log, only: %i[ index show destroy ] do
        post "revert", to: "audit_log#revert", on: :member
      end
    end
  end

  get "search", to: "search#index"
  devise_for :users
  resources :users

  # HACK: extremely hacky way of routing, do not touch unless you want to experience lots of pain
  resources :pages
  resources :page_assets, only: %i[ index show destroy ] do
    post :upload_image, on: :collection
  end
  resources :page_templates do
    get "json", to: "page_templates#json", on: :member
  end

  resources :page_categories
  resources :page_categories, only: :none, path: "/" do
    get ":page_id", to: "pages#show", as: :page, on: :member
    # resources :pages, on: :member
  end
end

app/models/page_template.rb
class PageTemplate < ApplicationRecord
  has_paper_trail ignore: :updated_at

  validates_presence_of :name
  validates_uniqueness_of :name
  validates_presence_of :template

  def self.ransackable_attributes(auth_object = nil)
    [ "name" ]
  end

  def self.ransackable_associations(auth_object = nil)
    ["versions"]
  end
end

app/controllers/page_templates_controller.rb
class PageTemplatesController < ApplicationController
  before_action :check_for_user
  before_action :set_page_template, only: %i[ show edit update destroy json ]

  # GET /page_templates or /page_templates.json
  def index
    @page_templates = policy_scope(PageTemplate)
  end

  # GET /page_templates/1 or /page_templates/1.json
  def show
    authorize @page_template
  end

  # GET /page_templates/new
  def new
    @page_template = authorize PageTemplate.new
  end

  # GET /page_templates/1/edit
  def edit
    authorize @page_template
  end

  # POST /page_templates or /page_templates.json
  def create
    @page_template = authorize PageTemplate.new(page_template_params)

    respond_to do |format|
      if @page_template.save
        format.html { redirect_to page_template_url(@page_template), notice: "Page template was successfully created." }
        format.json { render :show, status: :created, location: @page_template }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @page_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /page_templates/1 or /page_templates/1.json
  def update
    authorize @page_template
    respond_to do |format|
      if @page_template.update(page_template_params)
        format.html { redirect_to page_template_url(@page_template), notice: "Page template was successfully updated." }
        format.json { render :show, status: :ok, location: @page_template }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @page_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /page_templates/1 or /page_templates/1.json
  def destroy
    authorize @page_template
    @page_template.destroy!

    respond_to do |format|
      format.html { redirect_to page_templates_url, notice: "Page template was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def json
    render json: @page_template
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page_template
      @page_template = policy_scope(PageTemplate).find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def page_template_params
      params.require(:page_template).permit(:name, :template)
    end
end

app/helpers/page_templates_helper.rb
module PageTemplatesHelper
end

app/views/page_templates/_form.html.erb
<%= simple_form_for(@page_template, data: { controller: "editor" }) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="card">
    <%= f.input :name, label: false, wrapper: false, placeholder: "Template Name", input_html: { class: "card-header fs-1 m-0 border-0 border-bottom text-center" } %>
    <div class="card-body">
      <%= f.hidden_field :template, id: "content_hidden" %>
      <%= f.label "Template Content", class: "form-label optional" %>
      <div class="border rounded mb-3" id="content" data-editor-target="content"></div>
    </div>

    <div class="card-footer">
      <div class="card-footer-btn-group">
        <%= f.button :submit %>
        <%= yield %>
      </div>
    </div>
  </div>
<% end %>

app/views/page_templates/_page_template.html.erb
<div class="card h-100">
  <div class="card-body text-center d-flex justify-content-center align-items-center">
    <h4><%= page_template.name %></h4>
  </div>
  <div class="card-footer">
    <div class="card-footer-btn-group">
      <%= link_to "Show this page template", page_template_path(page_template), class: "btn" %>
      <%= link_to "Edit this page template", edit_page_template_path(page_template), class: "btn" %>
      <%= link_to "Destroy this page template", page_template, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn" %>
    </div>
  </div>
</div>

app/views/page_templates/edit.html.erb
<%= content_for :title do %>
  Edit Page Template • <%= @page_template.name %>
<% end %>

<div class="card">
  <div class="card-body">
    <h1 class="text-center">Editing page template</h1>
  </div>
</div>

<%= render "form", page_template: @page_template do %>
  <%= link_to "Discard changes", @page_template, data: { turbo_method: :get, turbo_confirm: "Are you sure?" }, class: "btn" %>
<% end %>

app/views/page_templates/index.html.erb
<%= content_for :title do %>
  All Page Templates
<% end %>

<div class="card">
  <div class="card-body">
    <h1 class="text-center">Page Templates</h1>
  </div>
</div>

<div class="row">
  <% @page_templates.each do |template| %>
    <div class="col-md-4 mb-3">
      <%= render template %>
    </div>
  <% end %>
</div>

<% if current_user %>
  <%= link_to "New page template", new_page_template_path, class: "btn btn-cardlike w-100" %>
  <%= link_to "Back to Dashboard", settings_dashboard_index_path, class: "btn btn-cardlike w-100" %>
<% end %>

app/views/page_templates/new.html.erb
<%= content_for :title do %>
  New Page Template
<% end %>

<div class="card">
  <div class="card-body">
    <h1 class="text-center">New page template</h1>
  </div>
</div>

<%= render "form", page_template: @page_template do %>
  <%= link_to "Discard changes", page_templates_path, data: { turbo_method: :get, turbo_confirm: "Are you sure?" }, class: "btn" %>
<% end %>

app/views/page_templates/show.html.erb
<%= content_for :title do %>
  Page Template • <%= @page_template.name %>
<% end %>

<div class="card">
  <div class="card-header">
    <h1 class="text-center">
      <%= @page_template.name %>
    </h1>
  </div>
  <div class="card-body">
    <div class="col col-md-6 mx-auto">
      <%= render_content(@page_template.template) %>
    </div>
  </div>
  <div class="card-footer">
    <div class="card-footer-btn-group">
      <% if current_user %>
        <%= link_to "Edit page template", edit_page_template_path(@page_template), class: "btn" %>
        <%= link_to "Back to page templates", page_templates_path, class: "btn" %>
        <%= link_to "Destroy this page template", @page_template, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn" %>
      <% end %>
    </div>
  </div>
</div>