config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "welcome#index"

  get "about_us", to: "welcome#about"
  get "history", to: "welcome#history"
  get "news", to: "welcome#news"
  get "resources", to: "welcome#resources"

  # Errors routes
  match "/404", to: "errors#not_found", via: :all
  match "/418", to: "errors#teapot", via: :all
  match "/422", to: "errors#unprocessable_content", via: :all
  match "/500", to: "errors#internal_server", via: :all

  resources :dashboard, only: :index do
    collection do
      get :settings
      resources :audit_log, only: %i[ index show destroy ] do
        post "revert", to: "audit_log#revert", on: :member
      end
    end
  end

  get "search", to: "search#index"
  devise_for :users
  resources :users

  # HACK: extremely hacky way of routing, do not touch unless you want to experience lots of pain
  resources :pages
  resources :page_assets, only: %i[ index show destroy ] do
    post :upload_image, on: :collection
  end
  resources :page_templates do
    get "json", to: "page_templates#json", on: :member
  end

  resources :page_categories
  resources :page_categories, only: :none, path: "/" do
    get ":page_id", to: "pages#show", as: :page, on: :member
    # resources :pages, on: :member
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :check_for_user

  def index
  end

  def settings
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_dashboard_header.html.erb
<div class="card">
  <div class="card-body">
    <h1 class="text-center">Welcome <b><%= current_user.name %></b>!</h1>
    <% if current_user.admin %>
      <p class="text-center">You are logged in as an admin!</p>
    <% end %>
  </div>
</div>

<div class="card">
  <div class="card-body nav nav-pills">
    <%= link_to "Dashboard", dashboard_index_path, class: "nav-link #{"active" if current_page?(dashboard_index_path)}" %>
    <%= link_to "Settings", settings_dashboard_index_path, class: "nav-link #{"active" if current_page?(settings_dashboard_index_path)}" %>
    <%= link_to "Audit Logs", audit_log_index_path, class: "nav-link #{"active" if current_page?(audit_log_index_path)}" %>
  </div>
</div>

app/views/dashboard/audit_log.html.erb
<%= content_for :title do %>
  Audit Log
<% end %>

<%= render partial: 'dashboard_header' %>

<% if @logs.length == 0 %>
  <div class="card">
    <div class="card-body">
      <h2 class="text-center">There are no logs available!</h2>
    </div>
  </div>
<% end %>

<% @logs.order(created_at: :desc).each do |log| %>
  <%= render log %>
<% end %>

app/views/dashboard/index.html.erb
<%= content_for :title do %>
  Dashboard
<% end %>

<%= render partial: "dashboard_header" %>

<div class="row">
  <div class="d-flex flex-column col-md-4 mb-3">
    <div class="card h-100">
      <div class="card-header">
        <h3 class="text-center">Pages</h3>
      </div>
      <div class="card-body d-flex flex-column">
        <div class="row">
          <% Page.all.order(id: :desc).first(2).each do |page| %>
            <div class="col-md-6 mb-3">
              <%= render page %>
            </div>
          <% end %>
        </div>
        <% if Page.count - 2 > 0 %>
          <p>... and <%= Page.count - 2 %> more</p>
        <% end %>
      </div>
      <div class="card-footer">
        <div class="card-footer-btn-group">
          <%= link_to "New page", new_page_path, class: "btn" %>
          <%= link_to "View All Pages", pages_path, class: "btn" %>
        </div>
      </div>
    </div>
  </div>
  <div class="d-flex flex-column col-md-4 mb-3">
    <div class="card h-100">
      <div class="card-header">
        <h3 class="text-center">Assets</h3>
      </div>
      <div class="card-body d-flex flex-column">
        <div class="row">
          <% PageAsset.all.order(id: :desc).first(2).each do |page_asset| %>
            <div class="col-md-6 mb-3">
              <%= render page_asset %>
            </div>
          <% end %>
        </div>
        <% if PageAsset.count - 2 > 0 %>
          <p>... and <%= PageAsset.count - 2 %> more</p>
        <% end %>
      </div>
      <div class="card-footer">
        <div class="card-footer-btn-group">
          <%= link_to "View All Page Assets", page_assets_path, class: "btn" %>
        </div>
      </div>
    </div>
  </div>
  <div class="d-flex flex-column col-md-4 mb-3">
    <div class="card h-100">
      <div class="card-header">
        <h3 class="text-center">Recent Activities</h3>
      </div>
      <div class="card-body d-flex flex-column">
        <div class="row">
          <% PaperTrail::Version.all.order(created_at: :desc).first(2).each do |version| %>
            <div class="d-flex flex-column col-md-6 mb-3">
              <%= render version %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="card-footer">
        <div class="card-footer-btn-group">
          <%= link_to "View All Logs", audit_log_index_path, class: "btn" %>
        </div>
      </div>
    </div>
  </div>
</div>

<div>
  <%= link_to "Sign Out", destroy_user_session_path, data: { turbo_method: :delete }, class: "btn btn-cardlike w-100" %>
</div>

app/views/dashboard/settings.html.erb
<%= content_for :title do %>
  Site Settings
<% end %>

<%= render partial: "dashboard_header" %>

<div class="card">
  <div class="card-body">
    <h3>Page Categories:</h3>
    <%= link_to "New", new_page_category_path, class: "btn btn-secondary" %>
    <%= link_to "Show all", page_categories_path, class: "btn btn-secondary" %>
  </div>
</div>

<div class="card">
  <div class="card-body">
    <h3>Page Templates:</h3>
    <%= link_to "New", new_page_template_path, class: "btn btn-secondary" %>
    <%= link_to "Show all", page_templates_path, class: "btn btn-secondary" %>
  </div>
</div>

<div class="card">
  <div class="card-body">
    <h3>Users:</h3>
    <%= link_to "New", new_user_path, class: "btn btn-secondary" %>
    <%= link_to "Show all", users_path, class: "btn btn-secondary" %>
  </div>
</div>