config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "welcome#index"

  get "about_us", to: "welcome#about"
  get "history", to: "welcome#history"
  get "news", to: "welcome#news"
  get "resources", to: "welcome#resources"

  # Errors routes
  match "/404", to: "errors#not_found", via: :all
  match "/418", to: "errors#teapot", via: :all
  match "/422", to: "errors#unprocessable_content", via: :all
  match "/500", to: "errors#internal_server", via: :all

  resources :dashboard, only: :index do
    collection do
      get :settings
      resources :audit_log, only: %i[ index show destroy ] do
        post "revert", to: "audit_log#revert", on: :member
      end
    end
  end

  get "search", to: "search#index"
  devise_for :users
  resources :users

  # HACK: extremely hacky way of routing, do not touch unless you want to experience lots of pain
  resources :pages
  resources :page_assets, only: %i[ index show destroy ] do
    post :upload_image, on: :collection
  end
  resources :page_templates do
    get "json", to: "page_templates#json", on: :member
  end

  resources :page_categories
  resources :page_categories, only: :none, path: "/" do
    get ":page_id", to: "pages#show", as: :page, on: :member
    # resources :pages, on: :member
  end
end

app/models/page_category.rb
class PageCategory < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :history
  has_many :pages, dependent: :destroy

  validates_presence_of :name
  validates_uniqueness_of :name

  def should_generate_new_friendly_id?
    name_changed?
  end
end

app/controllers/page_categories_controller.rb
class PageCategoriesController < ApplicationController
  before_action :check_for_user
  before_action :set_page_category, only: %i[ show edit update destroy ]

  # GET /page_categories or /page_categories.json
  def index
    @page_categories = policy_scope(PageCategory)
  end

  # GET /page_categories/1 or /page_categories/1.json
  def show
  end

  # GET /page_categories/new
  def new
    @page_category = authorize PageCategory.new
  end

  # GET /page_categories/1/edit
  def edit
  end

  # POST /page_categories or /page_categories.json
  def create
    @page_category = authorize PageCategory.new(page_category_params)

    respond_to do |format|
      if @page_category.save
        format.html { redirect_to page_categories_url, notice: "Page category was successfully created." }
        format.json { render :show, status: :created, location: @page_category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @page_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /page_categories/1 or /page_categories/1.json
  def update
    respond_to do |format|
      if @page_category.update(page_category_params)
        format.html { redirect_to page_categories_url, notice: "Page category was successfully updated." }
        format.json { render :show, status: :ok, location: @page_category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @page_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /page_categories/1 or /page_categories/1.json
  def destroy
    @page_category.destroy!

    respond_to do |format|
      format.html { redirect_to page_categories_url, notice: "Page category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page_category
      @page_category = authorize policy_scope(PageCategory).friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def page_category_params
      params.require(:page_category).permit(:name)
    end
end

app/helpers/page_categories_helper.rb
module PageCategoriesHelper
end

app/views/page_categories/_form.html.erb
<%= simple_form_for(@page_category) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="card">
    <div class="card-body">
      <%= f.input :name %>
    </div>

    <div class="card-footer">
      <div class="card-footer-btn-group">
        <%= f.button :submit %>
        <%= yield %>
      </div>
    </div>
  </div>
<% end %>

app/views/page_categories/_page_category.html.erb
<div class="card h-100">
  <div class="card-body text-center d-flex justify-content-center align-items-center">
    <h4><%= page_category.name %></h4>
  </div>
  <div class="card-footer">
    <div class="card-footer-btn-group">
      <%= link_to "Show this page category", page_category_path(page_category), class: "btn" %>
      <%= link_to "Edit this page category", edit_page_category_path(page_category), class: "btn" %>
      <%= link_to "Destroy this page category", page_category, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn" %>
    </div>
  </div>
</div>

app/views/page_categories/edit.html.erb
<%= content_for :title do %>
  Edit Page Category • <%= @page_category.name %>
<% end %>

<div class="card">
  <div class="card-body">
    <h1 class="text-center">Editing page category</h1>
  </div>
</div>

<%= render "form", page: @page do %>
  <%= link_to "Discard changes", @page_category, data: { turbo_method: :get, turbo_confirm: "Are you sure?" }, class: "btn" %>
<% end %>

app/views/page_categories/index.html.erb
<%= content_for :title do %>
  All Page Categories
<% end %>

<div class="card">
  <div class="card-body">
    <h1 class="text-center">Page Categories</h1>
  </div>
</div>

<div class="row">
  <% @page_categories.each do |category| %>
    <div class="col-md-4 mb-3">
      <%= render category %>
    </div>
  <% end %>
</div>

<% if current_user %>
  <%= link_to "New page category", new_page_category_path, class: "btn btn-cardlike w-100" %>
  <%= link_to "Back to Dashboard", settings_dashboard_index_path, class: "btn btn-cardlike w-100" %>
<% end %>

app/views/page_categories/new.html.erb
<%= content_for :title do %>
  New Page Category
<% end %>

<div class="card">
  <div class="card-body">
    <h1 class="text-center">New page category</h1>
  </div>
</div>

<%= render "form", page_category: @page_category do %>
  <%= link_to "Discard changes", page_categories_path, data: { turbo_method: :get, turbo_confirm: "Are you sure?" }, class: "btn" %>
<% end %>

app/views/page_categories/show.html.erb
<%= content_for :title do %>
  Page Category • <%= @page_category.name %>
<% end %>

<div class="card">
  <div class="card-body">
    <h1 class="text-center">
      <%= @page_category.name %>
    </h1>
  </div>
</div>

<h4>Pages:</h4>
<div class="row">
  <% @page_category.pages.each do |page| %>
    <div class="col-md-4 mb-3">
      <%= render page do %>
        <%= link_to "Show this page", page_page_category_path(@page_category.slug, page.slug), class: "btn" %>
      <% end %>
    </div>
  <% end %>
</div>

<% if current_user %>
  <%= link_to "Edit page category", edit_page_category_path(@page_category), class: "btn btn-cardlike w-100" %>
  <%= link_to "Back to page categories", page_categories_path, class: "btn btn-cardlike w-100" %>
<% end %>