config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "welcome#index"

  get "about_us", to: "welcome#about"
  get "history", to: "welcome#history"
  get "news", to: "welcome#news"
  get "resources", to: "welcome#resources"

  # Errors routes
  match "/404", to: "errors#not_found", via: :all
  match "/418", to: "errors#teapot", via: :all
  match "/422", to: "errors#unprocessable_content", via: :all
  match "/500", to: "errors#internal_server", via: :all

  resources :dashboard, only: :index do
    collection do
      get :settings
      resources :audit_log, only: %i[ index show destroy ] do
        post "revert", to: "audit_log#revert", on: :member
      end
    end
  end

  get "search", to: "search#index"
  devise_for :users
  resources :users

  # HACK: extremely hacky way of routing, do not touch unless you want to experience lots of pain
  resources :pages
  resources :page_assets, only: %i[ index show destroy ] do
    post :upload_image, on: :collection
  end
  resources :page_templates do
    get "json", to: "page_templates#json", on: :member
  end

  resources :page_categories
  resources :page_categories, only: :none, path: "/" do
    get ":page_id", to: "pages#show", as: :page, on: :member
    # resources :pages, on: :member
  end
end

app/views/layouts/_alert.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-<%= type == "notice" ? "success" : type %> fade show alert-dismissible">
    <% if msg.kind_of?(Array) %>
      <% msg.each do |m| %>
        <%= m %>
        <br>
      <% end %>
    <% else %>
      <%= msg %>
    <% end %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer-format bg-body-tertiary">
  <div class="container py-5 col-12 col-md">
    <h3 class="fw-bold text-center">We are proudly sponsored by...</h5>
    <h5 class="fw-bold text-center">Strategic Partners</h5>
    <div class="row row-cols-2 row-cols-md-4 g-0 justify-content-center row-gap-3 mt-2">
      <div class="col my-auto text-center">
        <a href="https://www.caterpillar.com/" target="_blank">
          <%= image_tag "sponsors/caterpillar.png", alt: "Caterpillar Logo", class: "sponsor-image" %>
        </a>
      </div>
      <div class="col my-auto text-center">
        <a href="https://purduefirst.org/" target="_blank">
          <%= image_tag "sponsors/purduefirst.png", alt: "PFP Logo", class: "sponsor-image" %>
        </a>
      </div>
      <div class="col my-auto text-center">
        <a href="https://www.stratasys.com/en/" target="_blank">
          <%= image_tag "sponsors/stratasys.webp", alt: "Stratasys Logo", class: "sponsor-image" %>
        </a>
      </div>
      <div class="col my-auto text-center">
        <a href="https://www.wl.k12.in.us/" target="_blank">
          <%= image_tag "sponsors/wl.png", alt: "WL Logo", class: "sponsor-image" %>
        </a>
      </div>
      <div class="col my-auto text-center">
        <a href="https://sledgehammerinfosystems.com/" target="_blank">
          <%= image_tag "sponsors/sledgehammer.png", alt: "Sledgehammer Logo", class: "sponsor-image" %>
        </a>
      </div>
      <div class="col my-auto text-center">
        <a href="https://www.arconic.com/" target="_blank">
          <%= image_tag "sponsors/arconic.png", alt: "Arconic Logo", class: "sponsor-image" %>
        </a>
      </div>
      <div class="col my-auto text-center">
        <a href="https://candcdi.com/" target="_blank">
          <%= image_tag "sponsors/ccdi.png", alt: "CCDI Logo", class: "sponsor-image" %>
        </a>
      </div>
      <div class="col my-auto text-center">
        <h5>Westside Boiler Invasion Families & Alumni</h5>
      </div>
    </div>
    <h5 class="display-7 fw-bold mt-5 text-center">Gold Sponsors</h5>
    <div class="row row-cols-2 row-cols-md-4 g-0 justify-content-center row-gap-3 mt-2">
      <div class="col my-auto text-center">
        <a href="https://www.andymark.com/" target="_blank">
          <%= image_tag "sponsors/andymark.png", alt: "Andymark Logo", class: "sponsor-image" %>
        </a>
      </div>
      <div class="col my-auto text-center">
        <a href="https://9and8golf.com/" target="_blank">
          <%= image_tag "sponsors/98golf.png", alt: "9and8Golf Logo", class: "sponsor-image" %>
        </a>
      </div>
      <div class="col my-auto text-center">
        <a href="https://www.conexusindiana.com/resources/purdue-in-mac/" target="_blank">
          <%= image_tag "sponsors/inmac.png", alt: "In-MaC Logo", class: "sponsor-image" %>
        </a>
      </div>
      <div class="col my-auto text-center">
        <a href="https://ghaasfoundation.org/content/ghf/en/home.html" target="_blank">
          <%= image_tag "sponsors/genehaas.webp", alt: "GeneHaas Logo", class: "sponsor-image" %>
        </a>
      </div>
      <div class="col my-auto text-center">
        <a href="https://summitfinancialgroupofindiana.com/" target="_blank">
          <%= image_tag "sponsors/summit.svg", alt: "Summit Logo", class: "sponsor-image" %>
        </a>
      </div>
      <div class="col my-auto text-center">
        <a href="https://www.radianresearch.com/" target="_blank">
          <%= image_tag "sponsors/radian.png", alt: "Radian Logo", class: "sponsor-image" %>
        </a>
      </div>
    </div>
    <h5 class="display-7 fw-bold mt-5 text-center">Silver Sponsors</h5>
    <div class="row row-cols-1 row-cols-md-4 g-0 justify-content-center row-gap-3 mt-2">
      <div class="col my-auto text-center">
        <a href="https://www.oscarwinski.com/" target="_blank">
          <%= image_tag "sponsors/oscarwinski.png", alt: "Oscar Logo", class: "sponsor-image" %>
        </a>
      </div>
      <div class="col my-auto text-center">
        <a href="https://www.colorsinc.com/" target="_blank">
          <%= image_tag "sponsors/colorsinc.jpg", alt: "Colorsinc Logo", class: "sponsor-image" %>
        </a>
      </div>
      <div class="col my-auto text-center">
        <a href="https://selinc.com/" target="_blank">
          <%= image_tag "sponsors/sel.png", alt: "SEL Logo", class: "sponsor-image" %>
        </a>
      </div>
    </div>
    <%= image_tag "logo.png", alt: "WBI logo", height: "32px" %>
    <span class="ps-4 float-end" style="min-width: 100px;">
      <small class="d-block mb-2">Follow Us</small>
      <a class="text-black text-decoration-none" href="https://www.instagram.com/team461wbi/" target="_blank">
        <i class="bi bi-instagram fs-2"></i>
      </a>
      <a class="text-black text-decoration-none" href="https://twitter.com/frc461" target="_blank">
        <i class="bi bi-twitter-x fs-2"></i>
      </a>
      <a class="text-black text-decoration-none" href="https://www.facebook.com/WBI461/" target="_blank">
        <i class="bi bi-facebook fs-2"></i>
      </a>
      <a class="text-black text-decoration-none" href="https://www.youtube.com/@team461" target="_blank">
        <i class="bi bi-youtube fs-2"></i>
      </a>
      <a class="text-black text-decoration-none p-1" href="https://github.com/frc461" target="_blank">
        <i class="bi bi-github fs-2"></i>
      </a>
    </span>
    <small class="d-block mb-3 text-muted mt-3">&copy;2024 461 Boosters FIRST, Inc. dba Westside Robotics</small>
    <small class="d-block mb-3 text-muted">Contributions by Gerseneck, leo-minton, SomiSauce, yeoms25, ez500
      (<a class="text-dark" href="https://github.com/frc461/website-2024" target="_blank">Source</a>)
      <span class="float-end">
        <%= image_tag "sand.png", alt: "Wabi & Scarlet", height: "64px" %>
      </span>
    </small>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg sticky-top bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/"><%= image_tag "logo.png", height: "30px" %></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="<%= about_us_path %>">About Us</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= history_path %>">Team History</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= news_path %>">News</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= resources_path %>">Resources</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="https://westside-robotics.info/" target="_blank">Learn More</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="https://donate.boilerinvasion.org/" target="_blank">Donate</a>
        </li>
      </ul>
      <form class="d-flex" role="search" action="<%= search_path %>">
        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search" autocomplete=off>
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      <div class="mx-0 my-2 my-lg-0 mx-lg-2">
        <%= link_to "Dashboard", if current_user then dashboard_index_path else new_user_session_path end, class: "btn btn-secondary" %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %> | Westside Boiler Invasion</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag "favicon.svg" %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "layouts/navbar" %>
    <main class="container-fluid py-3">
      <%= render partial: "layouts/alert" %>
      <%= yield %>
    </main>
    <%= render partial: "layouts/footer" %>
  </body>
</html>